# need 4 gpus

project: dycoder
save_path: /mnt/scratch/home/ismayilz/project-dycoder/models
name: gsm-dycoder-gpt2

only_eval: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 5
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: null
seed: 0
resume: 0
bf16: False
train_path: data/gsm/gsm_train.json
val_path: data/gsm/gsm_valid.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 5
lr: !!float "1e-4"
weight_decay: 0.01