# need 4 gpus

project: dycoder
save_path: /mnt/scratch/home/ismayilz/project-dycoder/models
name: gsm-cot-qwen2.5-0.5b-e5

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: Qwen/Qwen2.5-0.5B
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/gsm/gsm_train.json
val_path: data/gsm/gsm_valid.json
reset_optimizer: False
batch_size_training: 4
debug: False
gradient_accumulation_steps: 4
num_epochs: 5
lr: !!float "1e-4"
weight_decay: 0.01
